AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'vlim-swagger-app

  Sample SAM Template for vlim-swagger-app

  '
Globals:
  Function:
    Timeout: 3
Parameters:
  S3BucketName:
    Type: String
    Description: The name of the S3 bucket in which the Swagger specification is stored
  StageName:
    Type: String
    Description: The name of the stage, e.g. "dev", "preprod", "prod"
    Default: dev
Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: vlim-swagger-app-api-${StageName}
      StageName:
        Ref: StageName
      Cors: '''*'''
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location:
              Fn::Join:
              - ''
              - - s3://
                - Ref: S3BucketName
                - /swagger.yaml
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: vlim-swagger-app-${StageName}-hello-world
      CodeUri: s3://vlim-swagger-app-bucket/0fc53e70d3aea824ad42c901bcf5a222
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestApi
            Path: /hello
            Method: GET
Outputs:
  ApiUrl:
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: RestApi
        - Fn::Sub: .execute-api.${AWS::Region}.amazonaws.com/${StageName}
